version: 2.1

orbs:
  maven: circleci/maven@1.4.1
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:17-ea-buster-node-browsers-legacy  # Utilisation de l'image Docker avec Java 17

    steps:
      - checkout  # Récupère le code source du dépôt

      # Exécution des tests unitaires avec Maven
      - run:
          name: Run Unit Tests
          command: mvn test -X
      - run:
          name: Generate Coverage Report
          command: mvn jacoco:report
      - run:
          name: Upload Coverage Report
          command: bash <(curl -s https://codecov.io/bash)

      # Génération de la Javadoc avec Maven
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
    deploy:
      docker:
          - image: circleci/node:10.16.0
      # Déploiement de la Javadoc sur GitHub Pages
      steps:
          - attach_workspace:
              at: .
          - run:
              name: Install and configure dependencies
              command: |
                npm install -g gh-pages
                git remote set-url origin https://${GITHUB_TOKEN}@github.com/FerrariAdrien/ceri-m1-techniques-de-test.git
                git config --global user.email "gadrew157@gmail.com"
                git config --global user.name "FerrariAdrien"
          - run:
              name: Deploy to GitHub Pages
              command: gh-pages -d target/site/apidocs
workflows: # Définition des workflows
  version: 2
#  upload-to-codecov:
#    jobs:
#      - build:
#          filters:
#            branches:
#              only: master
  maven_test:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
            requires:
              - build
            filters:
              branches:
                only: master
