version: 2.1

orbs:
  maven: circleci/maven@1.4.1
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:17-ea-buster-node-browsers-legacy  # Utilisation de l'image Docker avec Java 17

    steps:
      - checkout  # Récupère le code source du dépôt

      # Exécution des tests unitaires avec Maven
      - run:
          name: Run Unit Tests
          command: mvn test -X
      - run:
          name: Generate Coverage Report
          command: mvn jacoco:report
      - run:
          name: Upload Coverage Report
          command: bash <(curl -s https://codecov.io/bash)
      - run:
          name: Generate Checkstyle report
          command: mvn checkstyle:checkstyle
      - run:
          name: Deploy Checkstyle report to GitHub
          command: |
            git config user.name "CircleCI"
            git config user.email "circleci@example.com"
            git add target/site
            git commit -m "Deploy Checkstyle report"
            git push -f https://FerrariAdrien:$GITHUB_TOKEN@github.com/FerrariAdrien/ceri-m1-techniques-de-test.git master:gh-pages
workflows: # Définition des workflows
  version: 2
  upload-to-codecov:
    jobs:
      - build
      - filters:
          branches:
            only: master
  maven_test:
    jobs:
      - build:
          filters:
            branches:
              only: master
