version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:17-ea-buster-node-browsers-legacy  # Utilisation de l'image Docker avec Java 17

    steps:
      - checkout  # Récupère le code source du dépôt

      # Exécution des tests unitaires avec Maven
      - run:
          name: Run Unit Tests
          command: mvn test

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master